name: 😎 Style

on: [push]

jobs:
  style:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Access the repo
        uses: actions/checkout@v3
      - name: set up python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'
      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install poetry==1.8.2

      - name: Configure poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --hook-stage manual --all-files

      - name: black check
        run: poetry run python -m black --check src/


      - name: Unit test
        run: PYTHONPATH=./src/pyab_experiment poetry run pytest
